# Generated by Django 3.2.5 on 2021-07-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio2text',
            name='user',
        ),
    ]
