# Generated by Django 3.2.5 on 2021-07-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_audio2text_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio2text',
            name='created_at',
        ),
    ]
