# Generated by Django 3.2.5 on 2021-07-16 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_audio2text_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio2text',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
