# Generated by Django 3.2.5 on 2021-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_audio2text_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechanimation',
            name='graphme',
            field=models.CharField(default='NAN', max_length=30),
        ),
    ]
